[debian_servers]
home_server ansible_host="{{ lookup('env', 'SERVER_IP') }}"

[debian_servers:vars]
ansible_user="{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_port="{{ lookup('env', 'ANSIBLE_PORT') }}"