---
# Install unattended-upgrades to periodically and automatically install security patches.
- name: Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
  notify: Restart unattended-upgrades

- name: Ensure unattended-upgrades is enabled and running
  systemd:
    name: unattended-upgrades
    state: started
    enabled: true

# Install fail2ban to automatically block repeated failed login attempts.
- name: Install fail2ban
  apt:
    name:
      - fail2ban
    state: present

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: Restart fail2ban

- name: Ensure fail2ban is enabled and running
  systemd:
    name: fail2ban
    state: started
    enabled: true

# Install UFW (Uncomplicated Firewall).
- name: Install UFW
  apt:
    name: 
      - ufw
    state: present

# Default-deny all unsolicited incoming traffic.
- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

# Allow all outbound traffic by default.
- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow

# Allow SSH access
- name: Allow SSH traffic
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp
  notify:  Reload UFW

- name: Ensure UFW is enabled and running
  community.general.ufw:
    state: enabled