---
- name: Install Docker dependencies
  apt:
    name:
      - ca-certificates
    state: present

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts.distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

# Install docker to run containerized applications
- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Deploy Docker daemon config
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: Restart docker

- name: Ensure Docker is enabled and running
  systemd:
    name: docker
    state: started
    enabled: true

- name: Create shared Docker network
  community.docker.docker_network:
    name: gateway
    state: present