---
- name: Restart unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded