---
- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded
